books/urls.py
from django.urls import path, re_path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:book_id>/', views.get_book, name='view_book'),
    re_path(r'^delete/(?P<pk>[0-9]+)/$', views.delete_book, name='delete_book'),
    re_path(r'^delete/author/(?P<pk>[0-9]+)/$', views.delete_author, name='delete_author') #я это скопипастил, надеюсь работает
]

sitetwo/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import login_page, logout_page

urlpatterns = [
    path('admin/',   admin.site.urls),
    path('books/', include('books.urls')),
    path('index/', include('books.urls')),
    path('', login_page),
    path('logout', logout_page),
]

books/models.py
import datetime
from django.db import models
from django.utils import timezone

class Author(models.Model):
    Author_name = models.CharField(max_length = 20)
    def __str__(self):
        return self.Author_name

class Book(models.Model):
    book_name = models.CharField(max_length=100)
    book_author = models.ForeignKey(Author, on_delete= models.CASCADE)
    def __str__(self):
        return self.book_name

books/views.py
from contextlib import redirect_stderr
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.views.generic.edit import CreateView
from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect
from .models import Book, author


def index(request):
    if request.method == 'GET':
        book_list = Book.objects.order_by('-book_name')
        template = loader.get_template('index.html')
        context = {
            'book_list': book_list
        }
        return HttpResponse(template.render(context, request))
    if request.method == 'POST':
        current_request_name = request.POST.get('aname', '')
        current_request_surname = request.POST.get('surname', '')
        if current_request_name != None and current_request_surname != None:
            try:
                au = Author.objects.get(name=current_request_name, surname=current_request_surname)
            except:
                au = None
                pass
            if au == None:
                author = Author.objects.create(name=current_request_name, surname=current_request_surname)
        bname = request.POST.get('bname', '')
        if bname != None:
            text = request.POST.get('text', '')
            author = Author.objects.get(name=current_request_name, current_request_surname=surname)
            book = Book.objects.create(name=bname, text=text, author=author)
            print(bname)
            print(book.book_name)
            print(book.id)
        return redirect('/')

def get_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'book.html', {'book': book})

def delete_book(request, pk):
    book = get_object_or_404(Book, pk = pk)
    if request.method == 'POST':
        book.delete()
        return redirect('/')
    return render(request, 'index.html', {'book': book})


def delete_author(request, pk):
    authoreq = get_object_or_404(Author, pk=pk)  
    if request.method == 'POST':         
        authoreq.delete()
        book_list = Book.objects.order_by('-book_name')
        for i in book_list:
            if i.author == authoreq:
                i.delete()
        return redirect('/')

    return render(request, 'index.html', {'author': authoreq})


def login_page(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/index')
        return render(request, 'LOGIN.html')
    if request.method == 'POST':
        username = request.POST.get('login', '')
        password = request.POST.get('password', '')
        perm = request.POST.get('sel', '')

        if username == '' or password == '':
            return redirect('/')

        user = authenticate(username=username, password=password)
        content_type = ContentType.objects.get_for_model(Book)
        permission = Permission.objects.create(
            codename=perm,
            name='',
            content_type=content_type,
        )
        user.user_permissions.add(permission)

        if user is not None:
            login(request, user)
            return redirect('/index')
        else:
            return redirect('/')

def logout_page(request):
    if request.method == 'POST':
        logout(request)
    return redirect('/')

books/templates/book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Анекдот</title>
</head>
<body>
    <span class="p"><span class=fi></span>{{book.book_name}}</span>
</body>
</html>

books/templates/index.html
<html>
<head>
</head>
<body>
    {% if book_list %}
    <ul class="list-group">
    {% for book in book_list %}
    <ul class="list-group list-group-horizontal">
        <li class="list-group-item"><a href="/book/{{book.id}}"> {{ book.book_name }}</a> </li>
        <li class="list-group-item">{{ book.book_author.Author_name }} </li>
        <li class="list-group-item"><form action="{% url 'books:delete_book' book.id %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Удалить книгу">
        </form></li>
        <li class="list-group-item"><form action="{% url 'books:delete_author' book.book_author.id %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Удалить автора">
        </form></li>
    </ul>
    {% endfor %}
    </ul>
    <input type="text" name="surname" class="form-control" placeholder="Введите фамилию:"/><br>
    <label>Книга:</label>
    <input type="text" name="bname" class="form-control" placeholder="Введите название:" /><br>
    <input type="text" name="text" class="form-control" id="exampleFormControlTextarea1" rows="5" placeholder="Введите текст:" /><br>
    <input type="submit"  class="btn btn-primary" value="Сохранить">
    {% else %}
    <p>No books are available.</p>
    {% endif %}
</body>
</html>